// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdeiUWnlEzkFBL97CQo2dXGOHtnjjjw-Q',
    appId: '1:292140891111:web:841410ffa07e0cadfd5b42',
    messagingSenderId: '292140891111',
    projectId: 'crudtutorial-e263c',
    authDomain: 'crudtutorial-e263c.firebaseapp.com',
    storageBucket: 'crudtutorial-e263c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGpa1reAPk3s8BPc7MV7roGzRTf9G1XXk',
    appId: '1:292140891111:android:3ebf55379bc00bc6fd5b42',
    messagingSenderId: '292140891111',
    projectId: 'crudtutorial-e263c',
    storageBucket: 'crudtutorial-e263c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4bug8AK7N2cInOzmOPsumpz3Xw5jNXIc',
    appId: '1:292140891111:ios:213b953dcee3517efd5b42',
    messagingSenderId: '292140891111',
    projectId: 'crudtutorial-e263c',
    storageBucket: 'crudtutorial-e263c.appspot.com',
    iosBundleId: 'com.example.firebasecrudtute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4bug8AK7N2cInOzmOPsumpz3Xw5jNXIc',
    appId: '1:292140891111:ios:213b953dcee3517efd5b42',
    messagingSenderId: '292140891111',
    projectId: 'crudtutorial-e263c',
    storageBucket: 'crudtutorial-e263c.appspot.com',
    iosBundleId: 'com.example.firebasecrudtute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdeiUWnlEzkFBL97CQo2dXGOHtnjjjw-Q',
    appId: '1:292140891111:web:a14971cc5a52041bfd5b42',
    messagingSenderId: '292140891111',
    projectId: 'crudtutorial-e263c',
    authDomain: 'crudtutorial-e263c.firebaseapp.com',
    storageBucket: 'crudtutorial-e263c.appspot.com',
  );
}
